name: Build ARMv5 Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Скачиваем код вашего репозитория (где лежит Dockerfile и entrypoint.sh)
      - name: Checkout your repository
        uses: actions/checkout@v4

      # 2. Скачиваем исходники Xray в папку xray-src через официальный экшен
      - name: Checkout Xray Source
        uses: actions/checkout@v4
        with:
          repository: XTLS/Xray-core
          path: xray-src
          fetch-depth: 1

      # 3. Скачиваем исходники tun2socks в папку tun2socks-src через официальный экшен
      - name: Checkout tun2socks Source
        uses: actions/checkout@v4
        with:
          repository: xjasonlyu/tun2socks
          path: tun2socks-src
          fetch-depth: 1

      # 4. Настраиваем эмуляторы архитектур
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 5. Инициализируем сборщик Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6. Авторизуемся на Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7. Запускаем сборку контейнера комбайна под arm/v5
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v5
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xray-tun2socks:latest
