name: Build ARMv5 Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your code
        uses: actions/checkout@v4

      # Скачиваем исходный код Xray на быстром и стабильном хосте
      - name: Clone Xray Source
        run: git clone --depth 1 https://github.com xray-src

      # Скачиваем исходный код tun2socks на быстром и стабильном хосте
      - name: Clone tun2socks Source
        run: git clone --depth 1 https://github.com tun2socks-src

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v5
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xray-tun2socks:latest
